### PR TITLE
API phpunit 9 support

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue: https://github.com/silverstripe/silverstripe-framework/issues/10019

### CODE REVIEW

**Review by unclecheese — APPROVED** [review]
LGTM

**Review by maxime-rainville — COMMENTED** [review]
Build is failing linting and behat test, but those failures look pre-existing. PHP8 builds are happy at least. I'm happy to merge as is since this is technically still in alpha and the failures are pre-existing.

**Comment by emteknetnz** [comment]
Oh right, master branch has a custom matrix.  Have added PGSQL to it.

**Review by maxime-rainville — APPROVED** [review]
Tho other two failures are pre-existing.

**Pull request merged**
