### PR TITLE
Feature #167: support persisted query

### PR DESCRIPTION
**Pull request by zzdjk6**

### CODE REVIEW

**Comment by zzdjk6** [comment]
Wow, thanks for reviewing and commenting my PR in such a detail level :)

I will refactor this solution according to the feedbacks (e.g., move it to Manager to support to multi-schema, etc.)

**Comment by zzdjk6** [comment]
@unclecheese I have refactored the solution so that it can support multi-schema feature now. And by abstracting the "QueryMappingProvider", the actual implementation can be injected and customized in a more flexible way (plus three ready-to-use provider class with config). I also rewrote the test code, please have a look, thanks :)

**Comment by zzdjk6** [comment]
I write a blog to introduce this feature in detail, hope it would be helpful: https://medium.com/@zzdjk6/persisted-graphql-query-with-axios-and-silverstripe-4-87126e0765e8

**Comment by unclecheese** [comment]
@zzdjk6 Can you give me write access to your PR branch? I'm trying to push up a few changes. This will reopen as soon as I push them. :)

**Comment by unclecheese** [comment]
Have moved to https://github.com/silverstripe/silverstripe-graphql/pull/179

Will give you write access, @zzdjk6

**Comment by zzdjk6** [comment]
@unclecheese Thanks for keep improving this feature and I will follow the latest changes on #179 :)

**Pull request closed without merging**
