### PR TITLE
FIX: NestedInputBuilder doesn't work with nested '*'

### PR DESCRIPTION
**Pull request by GuySartorelli**
Supercedes https://github.com/silverstripe/silverstripe-graphql/pull/536 and includes requested changes mentioned in that PR

## Issue
- https://github.com/silverstripe/silverstripe-graphql/issues/535

### CODE REVIEW

**Review by sabina-talipova — COMMENTED** [review]
Is it possible to add an additional test to check the case that was stated in the initial issue.

**Comment by GuySartorelli** [comment]
I thought the answer was going to be "yes, easy peasy" but it turns out that there's something weird about the way test schemas are built which differs in some way from normal schemas.... 
I've created [a new issue](https://github.com/silverstripe/silverstripe-graphql/issues/539) to cover that. Until that issue is resolved, I don't think there's any way to add a test for this - but I don't think this bug fix should be held back by that, since it is likely that will be a complex issue to resolve.

**Review by sabina-talipova — APPROVED** [review]
LGTM

**Comment by sabina-talipova** [comment]
@GuySartorelli, I've already approved. I couldn't reproduce issue by using provided code example in main ticket. But I have a question regarding [new issue that you opened](https://github.com/silverstripe/silverstripe-graphql/issues/539). 
Does not seem to you that you get the same Exception that was mentioned in the main ticket? Did you apply your test to this solution? 
Thank you.

**Comment by GuySartorelli** [comment]
> I couldn't reproduce issue by using provided code example in main ticket

Did you use [this example](https://github.com/silverstripe/silverstripe-graphql/issues/535#issuecomment-1586558963) and did you both [activate the default schema](https://docs.silverstripe.org/en/5/developer_guides/graphql/getting_started/activating_the_server/) and [tell graphql where to look for your models file](https://docs.silverstripe.org/en/5/developer_guides/graphql/getting_started/configuring_your_schema/#avoid-config-flushes)?

> I have a question regarding https://github.com/silverstripe/silverstripe-graphql/issues/539 ... Does not seem to you that you get the same Exception that was mentioned in the main ticket? Did you apply your test to this solution?

That's actually exactly the problem. In that issue, the schema example doesn't cause _any_ exception when used outside of a test context. But when used in a test, it gets the exception mentioned in that issue - which is indeed a _different exception_ than the one this PR is fixing. So there's something about the way tests set up or build schemas that's different from the normal execution, which is causing that exception when no exception should be thrown.

**Comment by sabina-talipova** [comment]
> Did you use https://github.com/silverstripe/silverstripe-graphql/issues/535#issuecomment-1586558963 and did you both [activate the default schema](https://docs.silverstripe.org/en/5/developer_guides/graphql/getting_started/activating_the_server/) and [tell graphql where to look for your models file](https://docs.silverstripe.org/en/5/developer_guides/graphql/getting_started/configuring_your_schema/#avoid-config-flushes)?
Yes, I did.

**Pull request merged**
