### PR TITLE
FIX Allow new DB fields when flushing

### PR DESCRIPTION
**Pull request by GuySartorelli**
If an `Extension` adds a db field (especially if it's adding it to `SiteConfig`, I've noticed) after the initial dev/build, graphql will throw an exception on dev/build.
This PR allows treats that exception the same as it does for missing tables/relations.

### CODE REVIEW

**Review by emteknetnz — APPROVED** [review]

**Review by emteknetnz — CHANGES_REQUESTED** [review]
Missing github actions ci run - could we get that merged first then rerun this?

Looks like the PR to put it in targetted the wrong branch (3.8) - you can create a cherry-pick backport PR and self-merge it

**Comment by GuySartorelli** [comment]
Added in https://github.com/silverstripe/silverstripe-graphql/pull/486

**Comment by emteknetnz** [comment]
Re-ran.  There's an existing graphql failure on the php8 job - we should still fix now though

https://app.travis-ci.com/github/silverstripe/silverstripe-graphql/jobs/575478497

**Comment by GuySartorelli** [comment]
I will fix the unrelated broken test in a separate PR.

**Pull request merged**
