### PR TITLE
BUGFIX: Throw on duplicate derived model names

### PR DESCRIPTION
**Pull request by unclecheese**
Resolves: https://github.com/silverstripe/silverstripe-graphql/issues/403

### CODE REVIEW

**Comment by kinglozzer** [comment]
I get an infinite loop somewhere when running a (web) `dev/build?flush` after this change - I’ve narrowed it down to this PR.

I _do_ have a duplicate derived name, which I was working around with this:

```yml
SilverStripe\GraphQL\Schema\Schema:
  schemas:
    admin:
      config:
        modelConfig:
          DataObject:
            type_mapping:
              App\Model\Page: AppPage
```

I tried removing that, but I still get an infinite loop rather than a warning about duplicate names 😞

**Comment by unclecheese** [comment]
Can you move that type_mapping to the main schema config, eg config.yml and use "typeMapping" instead?

**Comment by kinglozzer** [comment]
So the config in e.g. app/_graphql/config.yml? It’s for the admin schema
though, so will that work or will I have to set up a second config
directory for the admin schema?

I’ll give it a shot tomorrow, thanks!

**Comment by kinglozzer** [comment]
Okay that does fix it:

```yml
SilverStripe\GraphQL\Schema\Schema:
  schemas:
    admin:
      config:
        typeMapping:
          App\Model\Page: AppPage
```

I’ll create an issue for the infinite loop thing. Thanks and Merry Christmas @unclecheese 🎄

**Pull request merged**
