### PR TITLE
ENH PHP 8.1 compatibility fix

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/silverstripe-framework/issues/10294

### CODE REVIEW

**Review by GuySartorelli — APPROVED** [review]
Merge on green

**Comment by emteknetnz** [comment]
Behat failures are existing

**Review by GuySartorelli — COMMENTED** [review]
The only failure in travis is pre-existing and therefore not related to this PR.

@emteknetnz Just not sure what the .travis.yml changes are for?

**Comment by emteknetnz** [comment]
Deprecation issues
https://app.travis-ci.com/github/silverstripe/silverstripe-graphql/jobs/568487607#L1215

There was also a sporadic segmentation fault on phpcoverage, so I've disabled that

**Comment by GuySartorelli** [comment]
> Deprecation issues

That's all from the changes in `ExtensionLoader.php` though, right? The changes to `.travis.yml` don't resolve those, I think?

The changes in `.travis.yml` go beyond just removing `PHPUNIT_COVERAGE_TEST=1` so I'm just trying to understand what all the other changes there are for.

**Review by GuySartorelli — APPROVED** [review]
Was hoping for an explanation of why those changes were made... I don't see any reason for them?
That said it doesn't change the coverage, so it's fine. Will merge.

**Pull request merged**
