### PR TITLE
FIX DataObjectScaffolder is now injectable, and typos in readme are fixed

### PR DESCRIPTION
**Pull request by robbieaverill**
The context key is `currentUser`, so updated the examples to reflect this. Also the indentation level for `resolver` is important, and I've made the DataObjectScaffolder instantiation go through injector.

### CODE REVIEW

**Comment by dhensby** [comment]
Ideally these two changes would be separate commits, or even PRs

**Comment by robbieaverill** [comment]
Yeah you're right, sorry =(

**Comment by dhensby** [comment]
Mind splitting the commit and then we can merge :)

**Comment by robbieaverill** [comment]
Done, cheers

**Comment by dhensby** [comment]
thank you

**Pull request merged**
